config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 users/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 users/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                users/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            users/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           users/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                users/passwords#update
#                           PUT    /users/password(.:format)                                                                users/passwords#update
#                           POST   /users/password(.:format)                                                                users/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         users/registrations#update
#                           PUT    /users(.:format)                                                                         users/registrations#update
#                           DELETE /users(.:format)                                                                         users/registrations#destroy
#                           POST   /users(.:format)                                                                         users/registrations#create
#                      root GET    /                                                                                        home_pages#home
#       the_absent_students GET    /students/the_absent(.:format)                                                           students#the_absent_index
#    supplementary_students GET    /students/supplementary(.:format)                                                        students#supplementary_index
#                  students GET    /students(.:format)                                                                      students#index
#                           POST   /students(.:format)                                                                      students#create
#               new_student GET    /students/new(.:format)                                                                  students#new
#              edit_student GET    /students/:id/edit(.:format)                                                             students#edit
#                   student GET    /students/:id(.:format)                                                                  students#show
#                           PATCH  /students/:id(.:format)                                                                  students#update
#                           PUT    /students/:id(.:format)                                                                  students#update
#                           DELETE /students/:id(.:format)                                                                  students#destroy
#                  subjects GET    /subjects(.:format)                                                                      subjects#index
#                           POST   /subjects(.:format)                                                                      subjects#create
#               new_subject GET    /subjects/new(.:format)                                                                  subjects#new
#              edit_subject GET    /subjects/:title/edit(.:format)                                                          subjects#edit
#                   subject GET    /subjects/:title(.:format)                                                               subjects#show
#                           PATCH  /subjects/:title(.:format)                                                               subjects#update
#                           PUT    /subjects/:title(.:format)                                                               subjects#update
#                           DELETE /subjects/:title(.:format)                                                               subjects#destroy
#               absent_days GET    /absent_days(.:format)                                                                   absent_days#index
#                           POST   /absent_days(.:format)                                                                   absent_days#create
#            new_absent_day GET    /absent_days/new(.:format)                                                               absent_days#new
#           edit_absent_day GET    /absent_days/:id/edit(.:format)                                                          absent_days#edit
#                absent_day GET    /absent_days/:id(.:format)                                                               absent_days#show
#                           PATCH  /absent_days/:id(.:format)                                                               absent_days#update
#                           PUT    /absent_days/:id(.:format)                                                               absent_days#update
#                           DELETE /absent_days/:id(.:format)                                                               absent_days#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                   passwords: 'users/passwords' }
  root to: 'home_pages#home'
  resources :users, only: [:index, :destroy]

  resources :students do
    collection do
      get '/the_absent' => 'students#the_absent_index'
      get '/supplementary' => 'students#supplementary_index'
    end
  end
  resources :subjects, param: :title
  resources :absent_days
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  grade      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  grade_id   :integer
#

class Student < ApplicationRecord
  has_many :subject_students, dependent: :destroy
  has_many :subjects, through: :subject_students

  has_many :absent_days, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :grade, presence: true, length: { maximum: 10 }
  validates :grade_id, presence: true

  GRADES = ["中１", "中２", "中３"]


  def add_subject(subject)
    subjects << subject
  end

  def remove_subject(subject)
    subject_students.find_by(subject_id: subject.id).destroy
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]


  def index
    if params[:grade].present?
      @search = Student.ransack(params[:q])
      @students = @search.result.where(grade_id: params[:grade]).page(params[:page]).order(:grade_id)
      @all_students = @search.result.where(grade_id: params[:grade])
    else
      @search = Student.ransack(params[:q])
      @students = @search.result.page(params[:page]).per(10).order(:grade_id)
      @all_students = @search.result
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def index_by_grades
    @students = Student.where("grade_id = ?", params[:id])
  end

  def supplementary_index
    @absent_days = AbsentDay.includes(:student).supplementary
  end

  def the_absent_index
    @absent_days = AbsentDay.includes(:student)
  end

  def new
    @student = Student.new
  end

  def create
    set_params_for_registeration
    @student = Student.new(student_params)
    if @student.save
      add_subject if params[:student][:subject].present?
      flash[:success] = "新規生徒を登録しました。"
      redirect_to student_path(@student.id)
    else
      render 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    set_params_for_registeration
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      remove_subject
      add_subject if params[:student][:subject].present?
      flash[:success] = "生徒情報を編集しました"
      redirect_to student_path(@student.id)
    else
      render 'edit'
    end
  end

  def destroy
    Student.find(params[:id]).destroy
    flash[:success] = "生徒情報を削除しました。"
    redirect_to students_path
  end

  private
    def student_params
      params.require(:student).permit(:name, :grade, :grade_id)
    end

    def set_params_for_registeration
      case params[:student][:grade]
      when '中１'
        params[:student][:grade_id] = 1
      when '中２'
        params[:student][:grade_id] = 2
      when '中３'
        params[:student][:grade_id] = 3
      end
    end

    def add_subject
      params[:student][:subject].each do |subject|
        subject = Subject.find_by(title: subject)
        @student.add_subject(subject)
      end
    end

    def remove_subject
      @student.subjects.each do |subject|
        @student.remove_subject(subject)
      end
    end
end

app/views/students/edit.html.erb
<%= provide(:title, "生徒情報編集") %>

<%= render 'shared/form', button_title: "編集", student: @student, title: "生徒情報編集" %>

app/views/students/index.html.erb
<% provide(:title, "生徒一覧")%>

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <%= link_to "中１", students_path(params: { grade: 1 }) %>　|　
      <%= link_to "中２", students_path(params: { grade: 2 }) %>　|　
      <%= link_to "中３", students_path(params: { grade: 3 }) %>　|　
      <%= link_to "全生徒", students_path %>
    </div>
    <div class="collapse navbar-collapse justify-content-end">
      <form class="navbar-form">
        <div class="input-group no-border">
          <%= search_form_for @search do |form| %>
            <%= form.text_field :name_cont, placeholder: "生徒検索...", class: "form-control" %>
            <%= button_tag class: "btn btn-white btn-round btn-just-icon" do %>
              <i class="material-icons">search</i>
            <% end %>
          <% end %>
        </div>
      </form>
    </div>
  </div>
</nav>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-primary">
            <h4 class="card-title mt-0"><%= index_title_for_students(params[:grade], @all_students) %></h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    学年
                  </th>
                  <th>
                    名前
                  </th>
                </thead>
                <tbody>
                  <% @students.each do |student| %>
                    <tr>
                      <td><%= student.grade %></td>
                      <td><%= link_to student.name, student_path(student.id) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <%= paginate @students %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<% provide(:title, "新規生徒登録") %>

<%= render 'shared/form', button_title: "登録", student: @student, title: "新規生徒登録" %>

app/views/students/show.html.erb
<% provide(:title, "生徒情報")%>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">生徒情報</h4>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-5">
                <div class="form-group">
                <label class="bmd-label-floating">名前:</label><br>
                  <%= @student.name %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                <label class="bmd-label-floating">学年:</label><br>
                  <%= @student.grade %>
                </div
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">選択科目:</label><br>
                  <% @student.subjects.each do |subject| %>
                    <%= link_to subject.title, subject_path(title: subject.title) %><br>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
　　
<%= link_to "欠席登録", new_absent_day_path(student_id: @student.id) %>
<% if current_user.admin? %>
  　｜　
  <%= link_to "編集", edit_student_path(@student.id) %>　｜　
  <%= link_to "削除", student_path(@student.id), method: :delete, data: { confirm: "生徒情報を削除しますか？" } %>
<% end %>

app/views/students/supplementary_index.html.erb
<% provide(:title, "補習者未実施者一覧") %>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-danger">
            <h4 class="card-title mt-0">補習未実施者一覧</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    日付
                  </th>
                  <th>
                    学年
                  </th>
                  <th>
                    名前
                  </th>
                  <th>
                    科目
                  </th>
                  <th></th>
                </thead>
                <tbody>
                  <% @absent_days.each do |absent_day| %>
                    <tr>
                      <td><%= absent_day.date %></td>
                      <td><%= absent_day.student_grade %></td>
                      <td><%= link_to absent_day.student_name, student_path(absent_day.student_id) %></td>
                      <td><%= absent_day.subject %></td>
                      <td><%= link_to "補習を完了する", absent_day_path(absent_day.id), method: :put, data: { confirm: "補習を完了しますか？" } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/the_absent_index.html.erb
<% provide(:title, "欠席者一覧") %>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-danger">
            <h4 class="card-title mt-0">欠席者一覧</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    日付
                  </th>
                  <th>
                    学年
                  </th>
                  <th>
                    名前
                  </th>
                  <th>
                    科目
                  </th>
                  <th></th>
                </thead>
                <tbody>
                  <% @absent_days.each do |absent_day| %>
                    <tr>
                      <td><%= absent_day.date %></td>
                      <td><%= absent_day.student_grade %></td>
                      <td><%= link_to absent_day.student_name, student_path(absent_day.student_id) %></td>
                      <td><%= absent_day.subject %></td>
                      <td><%= link_to "取消", absent_day_path(absent_day.id), method: :delete, data: { confirm: "取り消しますか？" } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>