config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 users/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 users/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                users/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            users/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           users/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                users/passwords#update
#                           PUT    /users/password(.:format)                                                                users/passwords#update
#                           POST   /users/password(.:format)                                                                users/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         users/registrations#update
#                           PUT    /users(.:format)                                                                         users/registrations#update
#                           DELETE /users(.:format)                                                                         users/registrations#destroy
#                           POST   /users(.:format)                                                                         users/registrations#create
#                      root GET    /                                                                                        home_pages#home
#       the_absent_students GET    /students/the_absent(.:format)                                                           students#the_absent_index
#    supplementary_students GET    /students/supplementary(.:format)                                                        students#supplementary_index
#                  students GET    /students(.:format)                                                                      students#index
#                           POST   /students(.:format)                                                                      students#create
#               new_student GET    /students/new(.:format)                                                                  students#new
#              edit_student GET    /students/:id/edit(.:format)                                                             students#edit
#                   student GET    /students/:id(.:format)                                                                  students#show
#                           PATCH  /students/:id(.:format)                                                                  students#update
#                           PUT    /students/:id(.:format)                                                                  students#update
#                           DELETE /students/:id(.:format)                                                                  students#destroy
#                  subjects GET    /subjects(.:format)                                                                      subjects#index
#                           POST   /subjects(.:format)                                                                      subjects#create
#               new_subject GET    /subjects/new(.:format)                                                                  subjects#new
#              edit_subject GET    /subjects/:title/edit(.:format)                                                          subjects#edit
#                   subject GET    /subjects/:title(.:format)                                                               subjects#show
#                           PATCH  /subjects/:title(.:format)                                                               subjects#update
#                           PUT    /subjects/:title(.:format)                                                               subjects#update
#                           DELETE /subjects/:title(.:format)                                                               subjects#destroy
#               absent_days GET    /absent_days(.:format)                                                                   absent_days#index
#                           POST   /absent_days(.:format)                                                                   absent_days#create
#            new_absent_day GET    /absent_days/new(.:format)                                                               absent_days#new
#           edit_absent_day GET    /absent_days/:id/edit(.:format)                                                          absent_days#edit
#                absent_day GET    /absent_days/:id(.:format)                                                               absent_days#show
#                           PATCH  /absent_days/:id(.:format)                                                               absent_days#update
#                           PUT    /absent_days/:id(.:format)                                                               absent_days#update
#                           DELETE /absent_days/:id(.:format)                                                               absent_days#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                   passwords: 'users/passwords' }
  root to: 'home_pages#home'
  resources :users, only: [:index, :destroy]

  resources :students do
    collection do
      get '/the_absent' => 'students#the_absent_index'
      get '/supplementary' => 'students#supplementary_index'
    end
  end
  resources :subjects, param: :title
  resources :absent_days
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  day        :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subject < ApplicationRecord
  has_many :subject_students, dependent: :destroy
  has_many :students, through: :subject_students

  validates :title, presence: true
  validates :day, presence: true

  SUBJECTS = ["中１　英語A", "中１　英語B", "中１　数学A", "中１　数学B", "中１　国語A", "中１　国語B",
              "中２　英語A", "中２　英語B", "中２　数学A", "中２　数学B", "中２　国語A", "中２　国語B",
              "中３　英語A", "中３　英語B", "中３　数学A", "中３　数学B", "中３　国語A", "中３　国語B"]


  scope :day_of_today, -> { where(day: I18n.l(Date.today, format: :day)) }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    if params[:day].present?
      @subjects = Subject.where(day: params[:day])
    else
      @subjects = Subject.all
    end
  end

  def show
    @subject = Subject.find_by(title: params[:title])
  end
end

app/views/subjects/index.html.erb
<% provide(:title, "科目一覧") %>

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <%= link_to "月", subjects_path(params: { day: "月"}) %>　|　
      <%= link_to "火", subjects_path(params: { day: "火" }) %>　|　
      <%= link_to "水", subjects_path(params: { day: "水" }) %>　|　
      <%= link_to "木", subjects_path(params: { day: "木" }) %>　|　
      <%= link_to "金", subjects_path(params: { day: "金" }) %>　|　
      <%= link_to "全科目", subjects_path %>
    </div>
  </div>
</nav>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-info">
            <h4 class="card-title mt-0"><%= index_title_for_subjects(params[:day]) %></h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    科目名
                  </th>
                  <th>
                    曜日
                  </th>
                  <th>
                    人数
                  </th>
                </thead>
                <tbody>
                  <% @subjects.each do |subject| %>
                    <tr>
                      <td><%= link_to subject.title, subject_path(subject.title), id: "subject-title" %></td>
                      <td><%= subject.day %>曜日</td>
                      <td><%= subject.students.count %>人</td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<% provide(:title, @subject.title) %>


<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-danger">
            <h4 class="card-title mt-0"><%= @subject.title %>　(<%= @subject.day %>)</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    名前
                  </th>
                </thead>
                <tbody>
                  <% @subject.students.each do |student| %>
                    <tr>
                      <td><%= link_to student.name, student_path(student.id) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>