config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 users/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 users/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                users/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            users/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           users/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                users/passwords#update
#                           PUT    /users/password(.:format)                                                                users/passwords#update
#                           POST   /users/password(.:format)                                                                users/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         users/registrations#update
#                           PUT    /users(.:format)                                                                         users/registrations#update
#                           DELETE /users(.:format)                                                                         users/registrations#destroy
#                           POST   /users(.:format)                                                                         users/registrations#create
#                      root GET    /                                                                                        home_pages#home
#       the_absent_students GET    /students/the_absent(.:format)                                                           students#the_absent_index
#    supplementary_students GET    /students/supplementary(.:format)                                                        students#supplementary_index
#                  students GET    /students(.:format)                                                                      students#index
#                           POST   /students(.:format)                                                                      students#create
#               new_student GET    /students/new(.:format)                                                                  students#new
#              edit_student GET    /students/:id/edit(.:format)                                                             students#edit
#                   student GET    /students/:id(.:format)                                                                  students#show
#                           PATCH  /students/:id(.:format)                                                                  students#update
#                           PUT    /students/:id(.:format)                                                                  students#update
#                           DELETE /students/:id(.:format)                                                                  students#destroy
#                  subjects GET    /subjects(.:format)                                                                      subjects#index
#                           POST   /subjects(.:format)                                                                      subjects#create
#               new_subject GET    /subjects/new(.:format)                                                                  subjects#new
#              edit_subject GET    /subjects/:title/edit(.:format)                                                          subjects#edit
#                   subject GET    /subjects/:title(.:format)                                                               subjects#show
#                           PATCH  /subjects/:title(.:format)                                                               subjects#update
#                           PUT    /subjects/:title(.:format)                                                               subjects#update
#                           DELETE /subjects/:title(.:format)                                                               subjects#destroy
#               absent_days GET    /absent_days(.:format)                                                                   absent_days#index
#                           POST   /absent_days(.:format)                                                                   absent_days#create
#            new_absent_day GET    /absent_days/new(.:format)                                                               absent_days#new
#           edit_absent_day GET    /absent_days/:id/edit(.:format)                                                          absent_days#edit
#                absent_day GET    /absent_days/:id(.:format)                                                               absent_days#show
#                           PATCH  /absent_days/:id(.:format)                                                               absent_days#update
#                           PUT    /absent_days/:id(.:format)                                                               absent_days#update
#                           DELETE /absent_days/:id(.:format)                                                               absent_days#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                   passwords: 'users/passwords' }
  root to: 'home_pages#home'
  resources :users, only: [:index, :destroy]

  resources :students do
    collection do
      get '/the_absent' => 'students#the_absent_index'
      get '/supplementary' => 'students#supplementary_index'
    end
  end
  resources :subjects, param: :title
  resources :absent_days
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert<%= type %>"><%= msg %></div>
<% end %>

app/views/layouts/_head.html.erb
<title><%= full_title(page_title: yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
<link rel="icon" type="image/png" href="/assets/img/favicon.png">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

app/views/layouts/_sidebar.html.erb
<div class="sidebar" data-color="purple" data-background-color="white" data-image="assets/img/sidebar-1.jpg">
  <div class="logo">
    <%= link_to "MANAGEMENT APP", root_path, class: "simple-text logo-normal" %>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="material-icons">dashboard</i>
          <p>トップページ</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to students_path, class: "nav-link" do %>
          <i class="material-icons">person</i>
          <p>生徒一覧</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to subjects_path, class: "nav-link" do %>
          <i class="material-icons">content_paste</i>
          <p>科目一覧</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to the_absent_students_path, class: "nav-link" do %>
          <i class="material-icons">person</i>
          <p>欠席者一覧</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to supplementary_students_path, class: "nav-link" do %>
          <i class="material-icons">person</i>
          <p>補習未実施者一覧</p>
        <% end %>
      </li>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to new_student_path, class: "nav-link" do %>
            <i class="material-icons">library_books</i>
            <p>新規生徒登録</p>
          <% end %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <i class="material-icons">person</i>
            <p><%= current_user.name %></p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
            <%= link_to "設定", edit_user_registration_path %>
            <div class="dropdown-divider"></div>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </div>
        </li>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <i class="material-icons">person</i>
            <p>管理者権限</p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
            <%= link_to "新規アカウント作成", "/users/sign_up" %>
            <%= link_to "アカウント削除", users_path %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <div class="wrapper">
      <%= render 'layouts/sidebar' %>
      <div class="content">
        <div class="container-fluid">
          <div class="main-panel">
            <%= render 'layouts/flash_message' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>